package com.example.compose
import androidx.compose.ui.graphics.Color

val bella_theme_light_primary = Color(0xFF9C423B)
val bella_theme_light_onPrimary = Color(0xFFFFFFFF)
val bella_theme_light_primaryContainer = Color(0xFFFFDAD6)
val bella_theme_light_onPrimaryContainer = Color(0xFF410002)
val bella_theme_light_secondary = Color(0xFF775653)
val bella_theme_light_onSecondary = Color(0xFFFFFFFF)
val bella_theme_light_secondaryContainer = Color(0xFFFFDAD6)
val bella_theme_light_onSecondaryContainer = Color(0xFF2C1513)
val bella_theme_light_tertiary = Color(0xFF715B2E)
val bella_theme_light_onTertiary = Color(0xFFFFFFFF)
val bella_theme_light_tertiaryContainer = Color(0xFFFEDFA6)
val bella_theme_light_onTertiaryContainer = Color(0xFF261900)
val bella_theme_light_error = Color(0xFFBA1A1A)
val bella_theme_light_errorContainer = Color(0xFFFFDAD6)
val bella_theme_light_onError = Color(0xFFFFFFFF)
val bella_theme_light_onErrorContainer = Color(0xFF410002)
val bella_theme_light_background = Color(0xFFFFFBFF)
val bella_theme_light_onBackground = Color(0xFF201A19)
val bella_theme_light_surface = Color(0xFFFFFBFF)
val bella_theme_light_onSurface = Color(0xFF201A19)
val bella_theme_light_surfaceVariant = Color(0xFFF5DDDB)
val bella_theme_light_onSurfaceVariant = Color(0xFF534341)
val bella_theme_light_outline = Color(0xFF857371)
val bella_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
val bella_theme_light_inverseSurface = Color(0xFF362F2E)
val bella_theme_light_inversePrimary = Color(0xFFFFB4AC)
val bella_theme_light_shadow = Color(0xFF000000)
val bella_theme_light_surfaceTint = Color(0xFF9C423B)
val bella_theme_light_outlineVariant = Color(0xFFD8C2BF)
val bella_theme_light_scrim = Color(0xFF000000)

val bella_theme_dark_primary = Color(0xFFFFB4AC)
val bella_theme_dark_onPrimary = Color(0xFF5F1412)
val bella_theme_dark_primaryContainer = Color(0xFF7E2B25)
val bella_theme_dark_onPrimaryContainer = Color(0xFFFFDAD6)
val bella_theme_dark_secondary = Color(0xFFE7BDB8)
val bella_theme_dark_onSecondary = Color(0xFF442927)
val bella_theme_dark_secondaryContainer = Color(0xFF5D3F3C)
val bella_theme_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val bella_theme_dark_tertiary = Color(0xFFE0C38C)
val bella_theme_dark_onTertiary = Color(0xFF3F2E04)
val bella_theme_dark_tertiaryContainer = Color(0xFF584419)
val bella_theme_dark_onTertiaryContainer = Color(0xFFFEDFA6)
val bella_theme_dark_error = Color(0xFFFFB4AB)
val bella_theme_dark_errorContainer = Color(0xFF93000A)
val bella_theme_dark_onError = Color(0xFF690005)
val bella_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val bella_theme_dark_background = Color(0xFF201A19)
val bella_theme_dark_onBackground = Color(0xFFEDE0DE)
val bella_theme_dark_surface = Color(0xFF201A19)
val bella_theme_dark_onSurface = Color(0xFFEDE0DE)
val bella_theme_dark_surfaceVariant = Color(0xFF534341)
val bella_theme_dark_onSurfaceVariant = Color(0xFFD8C2BF)
val bella_theme_dark_outline = Color(0xFFA08C8A)
val bella_theme_dark_inverseOnSurface = Color(0xFF201A19)
val bella_theme_dark_inverseSurface = Color(0xFFEDE0DE)
val bella_theme_dark_inversePrimary = Color(0xFF9C423B)
val bella_theme_dark_shadow = Color(0xFF000000)
val bella_theme_dark_surfaceTint = Color(0xFFFFB4AC)
val bella_theme_dark_outlineVariant = Color(0xFF534341)
val bella_theme_dark_scrim = Color(0xFF000000)


val bella_seed = Color(0xFFDB7D74)
