package com.example.bellavoice.ui.theme.ava
import androidx.compose.ui.graphics.Color

val ava_theme_light_primary = Color(0xFF006687)
val ava_theme_light_onPrimary = Color(0xFFFFFFFF)
val ava_theme_light_primaryContainer = Color(0xFFC1E8FF)
val ava_theme_light_onPrimaryContainer = Color(0xFF001E2B)
val ava_theme_light_secondary = Color(0xFF4D616C)
val ava_theme_light_onSecondary = Color(0xFFFFFFFF)
val ava_theme_light_secondaryContainer = Color(0xFFD1E6F3)
val ava_theme_light_onSecondaryContainer = Color(0xFF091E28)
val ava_theme_light_tertiary = Color(0xFF5F5A7D)
val ava_theme_light_onTertiary = Color(0xFFFFFFFF)
val ava_theme_light_tertiaryContainer = Color(0xFFE5DEFF)
val ava_theme_light_onTertiaryContainer = Color(0xFF1B1736)
val ava_theme_light_error = Color(0xFFBA1A1A)
val ava_theme_light_errorContainer = Color(0xFFFFDAD6)
val ava_theme_light_onError = Color(0xFFFFFFFF)
val ava_theme_light_onErrorContainer = Color(0xFF410002)
val ava_theme_light_background = Color(0xFFFBFCFE)
val ava_theme_light_onBackground = Color(0xFF191C1E)
val ava_theme_light_surface = Color(0xFFFBFCFE)
val ava_theme_light_onSurface = Color(0xFF191C1E)
val ava_theme_light_surfaceVariant = Color(0xFFDCE3E9)
val ava_theme_light_onSurfaceVariant = Color(0xFF40484C)
val ava_theme_light_outline = Color(0xFF71787D)
val ava_theme_light_inverseOnSurface = Color(0xFFF0F1F3)
val ava_theme_light_inverseSurface = Color(0xFF2E3133)
val ava_theme_light_inversePrimary = Color(0xFF74D1FF)
val ava_theme_light_shadow = Color(0xFF000000)
val ava_theme_light_surfaceTint = Color(0xFF006687)
val ava_theme_light_outlineVariant = Color(0xFFC0C7CD)
val ava_theme_light_scrim = Color(0xFF000000)

val ava_theme_dark_primary = Color(0xFF74D1FF)
val ava_theme_dark_onPrimary = Color(0xFF003548)
val ava_theme_dark_primaryContainer = Color(0xFF004D67)
val ava_theme_dark_onPrimaryContainer = Color(0xFFC1E8FF)
val ava_theme_dark_secondary = Color(0xFFB5C9D7)
val ava_theme_dark_onSecondary = Color(0xFF1F333D)
val ava_theme_dark_secondaryContainer = Color(0xFF364954)
val ava_theme_dark_onSecondaryContainer = Color(0xFFD1E6F3)
val ava_theme_dark_tertiary = Color(0xFFC8C2EA)
val ava_theme_dark_onTertiary = Color(0xFF302C4C)
val ava_theme_dark_tertiaryContainer = Color(0xFF474364)
val ava_theme_dark_onTertiaryContainer = Color(0xFFE5DEFF)
val ava_theme_dark_error = Color(0xFFFFB4AB)
val ava_theme_dark_errorContainer = Color(0xFF93000A)
val ava_theme_dark_onError = Color(0xFF690005)
val ava_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val ava_theme_dark_background = Color(0xFF191C1E)
val ava_theme_dark_onBackground = Color(0xFFE1E2E5)
val ava_theme_dark_surface = Color(0xFF191C1E)
val ava_theme_dark_onSurface = Color(0xFFE1E2E5)
val ava_theme_dark_surfaceVariant = Color(0xFF40484C)
val ava_theme_dark_onSurfaceVariant = Color(0xFFC0C7CD)
val ava_theme_dark_outline = Color(0xFF8A9297)
val ava_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val ava_theme_dark_inverseSurface = Color(0xFFE1E2E5)
val ava_theme_dark_inversePrimary = Color(0xFF006687)
val ava_theme_dark_shadow = Color(0xFF000000)
val ava_theme_dark_surfaceTint = Color(0xFF74D1FF)
val ava_theme_dark_outlineVariant = Color(0xFF40484C)
val ava_theme_dark_scrim = Color(0xFF000000)


val ava_seed = Color(0xFF9AC8E2)
